baseURL: "https://pradyumngoel.com/"
languageCode: en-us
title: Pradyumn Goel's Website
theme: PaperMod

params:
  defaultTheme: dark

  homeInfoParams:
    Title: "Hello, Whoever you are!"
    Content: "Welcome to my site, Where I talk about some gaming and post my projects."

  socialIcons:
    - name: github
      url: "https://github.com/pradyumngoel"
    - name: discord
      url: "https://discordapp.com/users/@Shadow442#7298"
    - name: youtube
      url: "https://www.youtube.com/channel/UCGyz4Jx-kxlwkHv09-_S9fA"

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: stories
      name: Stories
      url: /Categories/Stories/
      weight: 30
    - identifier: projects
      name: Projects
      url: /Categories/Projects/
      weight: 10
    - identifier: blog
      name: Blog
      url: /Categories/Blogging/
      weight: 20
      weight: 50
    - identifier: archives
      name: Archive
      url: /Archives/
      weight: 60
    - identifier: aboutme
      name: About Me
      url: /AboutMe/
      weight: 70
